# Use postgres/example user/password credentials
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      volumes:
        - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
