import type { Metadata } from 'next';
import { Inter, Montserrat } from 'next/font/google';
import '@/app/styles/globals.css';
import Navbar from '../components/Header';
import Footer from '../components/Footer';
import { Providers } from '../components/Providers';

// const inter = Inter({ subsets: ['latin'] });

const montserrat = Montserrat({
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={montserrat.className}>
				<Providers>
					{/* Header */}
					<Navbar />
					{children}
					{/* Footer */}
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
