import { Courgette, Montserrat, Poppins } from 'next/font/google';
// import sidebar form shadcn ui
import SideBar from '../components/sidebar/SideBar';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
// globals styles
import '../styles/globals.css';
import AdminHeader from '../components/header/AdminHeader';
import RightPannel from '../components/right-pannel/RightPannel';
import AdminAvatar from '../components/header/AdminAvatar';
import MinNav from '../components/Navs/MinNav';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const montserrat = Montserrat({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
	variable: '--font-montserrat',
});

const poppins = Poppins({
	weight: ['400', '500', '600', '700'],
	subsets: ['latin'],
	variable: '--font-poppins',
});

const courgette = Courgette({
	weight: ['400'],
	subsets: ['latin'],
	variable: '--font-courgette',
});

export const metadata = {
	title: 'Bristro Restaurant | Dashboard',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={`antialiased ${montserrat.variable} ${poppins.variable} ${courgette.variable}`}>
				<SidebarProvider>
					<AppSidebar />
					<main className='w-full'>
						<AdminHeader>
							<AdminAvatar />
						</AdminHeader>
						<MinNav />
						{children}
						<ToastContainer />
					</main>
					<RightPannel />
				</SidebarProvider>
			</body>
		</html>
	);
}
