import { Inter, Montserrat } from 'next/font/google';
import '@/app/styles/globals.css';

const montserrat = Montserrat({
	subsets: ['latin'],
});

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={montserrat.className}>{children}</body>
		</html>
	);
}
