export enum Routes {
	ROOT = '/',
	MENU = 'menu',
	RESERVATION = 'reservation',
	GALLERY = 'gallery',
	ABOUT = 'about',
	BLOG = 'blog',
	CONTACT = 'contact',
	AUTH = 'auth',
	CART = 'cart',
	DASHBOARD = 'dashboard',
	ALLPRODUCTS = 'product/list',
	ADDPRODUCT = 'product/add',
	EDITPRODUCT = 'product/edit',
	USERPROFILE = 'user/profile',
	ADDUSER = 'user/add',
	USERLIST = 'user/list',
}
