import type { Metadata } from 'next';
import { Courgette, Montserrat, Poppins } from 'next/font/google';
import { Providers } from './components/Providers';
// componetes
import Navbar from './components/header/Header';
import Footer from './components/Footer';
// globals style
import './globals.css';

const montserrat = Montserrat({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
	variable: '--font-montserrat',
});

const poppins = Poppins({
	weight: ['400', '500', '600', '700'],
	subsets: ['latin'],
	variable: '--font-poppins',
});

const courgette = Courgette({
	weight: ['400'],
	subsets: ['latin'],
	variable: '--font-courgette',
});

export const metadata: Metadata = {
	title: 'Bristro Restaurant',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`antialiased ${montserrat.variable} ${poppins.variable} ${courgette.variable}`}
			>
				<Providers>
					{/* Header */}
					<Navbar />
					{children}
					{/* Footer */}
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
