import type { Metadata } from 'next';
import { Inter, Montserrat } from 'next/font/google';
import './globals.css';
import Navbar from './components/Header';
import Footer from './components/Footer';
import { Providers } from './components/Providers';

const inter = Inter({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
	variable: '--font-inter',
});
const montserrat = Montserrat({
	weight: ['400'],
	subsets: ['latin'],
	variable: '--font-montserrat',
});

export const metadata: Metadata = {
	title: 'Bristro Restaurant',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased ${inter.variable} ${montserrat.variable}`}>
				<Providers>
					{/* Header */}
					<Navbar />
					{children}
					{/* Footer */}
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
